export const EMOJI_CATEGORIES = {
  "Dark & Sexy": ['😈', '👿', '🖤', '🥀', '🕸️', '🧛‍♀️', '💀', '💋', '💄', '🍷', '👠', '💃', '🍑', '🍆', '🍌', '🍒', '🍓', '🔥', '✨', '🥵', '🥺', '🤐', '🤫', '👀', '🫦', '💅', '⛓️', '🩸', '🥃', '🚬', '🛌', '🚿', '🧸', '👙', '👄', '👅', '🦴', '☠️', '🕴️', '🕵️‍♀️', '🌚', '🌑', '🌪️', '🌫️', '🎭', '🎪', '🎰', '🎲', '🎱', '🎮', '🎳', '🎯', '🎻', '🎷', '🎸', '🎹', '🎺', '🥁', '🎤', '🎧', '🎼', '🎬', '🎨', '🩰', '👯‍♀️', '👯‍♂️', '💃', '🕺', '🧗‍♀️', '🧗‍♂️', '🤺', '🏇', '⛷️', '🏂', '🏌️‍♀️', '🏌️‍♂️', '🏄‍♀️', '🏄‍♂️', '🚣‍♀️', '🚣‍♂️', '🏊‍♀️', '🏊‍♂️', '⛹️‍♀️', '⛹️‍♂️', '🏋️‍♀️', '🏋️‍♂️', '🚴‍♀️', '🚴‍♂️', '🚵‍♀️', '🚵‍♂️', '🤸‍♀️', '🤸‍♂️', '🤼‍♀️', '🤼‍♂️', '🤽‍♀️', '🤽‍♂️', '🤾‍♀️', '🤾‍♂️', '🤹‍♀️', '🤹‍♂️', '🧘‍♀️', '🧘‍♂️', '🛀', '🛌', '👭', '👫', '👬', '💏', '👩‍❤️‍💋‍👨', '👨‍❤️‍💋‍👨', '👩‍❤️‍💋‍👩', '💑', '👩‍❤️‍👨', '👨‍❤️‍👨', '👩‍❤️‍👩', '👪', '👨‍👩‍👧', '👨‍👩‍👧‍👦', '👨‍👩‍👦‍👦', '👨‍👩‍👧‍👧', '👨‍👨‍👦', '👨‍👨‍👧', '👨‍👨‍👧‍👦', '👨‍👨‍👦‍👦', '👨‍👨‍👧‍👧', '👩‍👩‍👦', '👩‍👩‍👧', '👩‍👩‍👧‍👦', '👩‍👩‍👦‍👦', '👩‍👩‍👧‍👧', '👨‍👦', '👨‍👦‍👦', '👨‍👧', '👨‍👧‍👦', '👨‍👧‍👧', '👩‍👦', '👩‍👦‍👦', '👩‍👧', '👩‍👧‍👦', '👩‍👧‍👧', '🗣️', '👤', '👥', '🫂', '👣', '🦰', '🦱', '🦳', '🦲'],
  "Smilies": ['😀', '😃', '😄', '😁', '😆', '😅', '🤣', '😂', '🙂', '🙃', '😉', '😊', '😇', '🥰', '😍', '🤩', '😘', '😗', '☺️', '😚', '😙', '😋', '😛', '😜', '🤪', '😝', '🤑', '🤗', '🤭', '🤫', '🤔', '🤐', '🤨', '😐', '😑', '😶', '😏', '😒', '🙄', '😬', '🤥', '😌', '😔', '😪', '🤤', '🥵', '🥶', '😱', '😨', '😰', '😥', '😓', '🤗', '🤔', '🤭', '🤫', '🤥', '😶', '😐', '😑', '😬', '🙄', '😯', '😮', '😲', '🥱', '😴', '🤤', '😪', '😵', '🤐', '🥴', '🤢', '🤮', '🤧', '😷', '🤒', '🤕', '🤑', '🤠', '😈', '👿', '👹', '👺', '🤡', '💩', '👻', '💀', '☠️', '👽', '👾', '🤖', '🎃', '😺', '😸', '😹', '😻', '😼', '😼', '😽', '🙀', '😿', '😾'],
  "People": ['👶', '👧', '🧒', '👦', '👩', '🧑', '👨', '👩‍🦱', '🧑‍🦱', '👨‍🦱', '👩‍🦰', '🧑‍🦰', '👨‍🦰', '👱‍♀️', '👱', '👱‍♂️', '👩‍🦳', '🧑‍🦳', '👨‍🦳', '👩‍🦲', '🧑‍🦲', '👨‍🦲', '🧔', '👵', '🧓', '👴', '👲', '👳‍♀️', '👳', '👳‍♂️', '🧕', '👮‍♀️', '👮', '👮‍♂️', '👷‍♀️', '👷', '👷‍♂️', '💂‍♀️', '💂', '💂‍♂️', '🕵️‍♀️', '🕵', '🕵️‍♂️', '👩‍⚕️', '🧑‍⚕️', '👨‍⚕️', '👩‍🌾', '🧑‍🌾', '👨‍🌾', '👩‍🍳', '🧑‍🍳', '👨‍🍳', '👩‍🎓', '🧑‍🎓', '👨‍🎓', '👩‍🎤', '🧑‍🎤', '👨‍🎤', '👩‍🏫', '🧑‍🏫', '👨‍🏫', '👩‍🏭', '🧑‍🏭', '👨‍🏭', '👩‍💻', '🧑‍💻', '👨‍💻', '👩‍💼', '🧑‍💼', '👨‍💼', '👩‍🔧', '🧑‍🔧', '👨‍🔧', '👩‍🔬', '🧑‍🔬', '👨‍🔬', '👩‍🎨', '🧑‍🎨', '👨‍🎨', '👩‍🚒', '🧑‍🚒', '👨‍🚒', '👩‍✈️', '🧑‍✈️', '👨‍✈️', '👩‍🚀', '🧑‍🚀', '👨‍🚀', '👩‍⚖️', '🧑‍⚖️', '👨‍⚖️', '👰', '🤵', '👸', '🤴', '🦸‍♀️', '🦸', '🦸‍♂️', '🦹‍♀️', '🦹', '🦹‍♂️', '🤶', '🎅', '🧙‍♀️', '🧙', '🧙‍♂️', '🧝‍♀️', '🧝', '🧝‍♂️', '🧛‍♀️', '🧛', '🧛‍♂️', '🧟‍♀️', '🧟', '🧟‍♂️', '🧞‍♀️', '🧞', '🧞‍♂️', '🧜‍♀️', '🧜', '🧜‍♂️', '🧚‍♀️', '🧚', '🧚‍♂️', '👼', '🤰', '🤱', '🙇‍♀️', '🙇', '🙇‍♂️', '💁‍♀️', '💁', '💁‍♂️', '🙅‍♀️', '🙅', '🙅‍♂️', '🙆‍♀️', '🙆', '🙆‍♂️', '🙋‍♀️', '🙋', '🙋‍♂️', '🧏‍♀️', '🧏', '🧏‍♂️', '🤦‍♀️', '🤦', '🤦‍♂️', '🤷‍♀️', '🤷', '🤷‍♂️', '🙎‍♀️', '🙎', '🙎‍♂️', '🙍‍♀️', '🙍', '🙍‍♂️', '💇‍♀️', '💇', '💇‍♂️', '💆‍♀️', '💆', '💆‍♂️', '🧖‍♀️', '🧖', '🧖‍♂️', '💅', '🤳', '💃', '🕺', '👯‍♀️', '👯', '👯‍♂️', '🕴', '👩‍🦽', '🧑‍🦽', '👨‍🦽', '👩‍🦼', '🧑‍🦼', '👨‍🦼', '🚶‍♀️', '🚶', '🚶‍♂️', '👩‍🦯', '🧑‍🦯', '👨‍🦯', '🧎‍♀️', '🧎', '🧎‍♂️', '🏃‍♀️', '🏃', '🏃‍♂️', '🧍‍♀️', '🧍', '🧍‍♂️', '👭', '🧑‍🤝‍🧑', '👬', '👫', '👩‍❤️‍👩', '💑', '👨‍❤️‍👨', '👩‍❤️‍💋‍👩', '💏', '👨‍❤️‍💋‍👨', '👪', '👨‍👩‍👧', '👨‍👩‍👧‍👦', '👨‍👩‍👦‍👦', '👨‍👩‍👧‍👧', '👨‍👨‍👦', '👨‍👨‍👧', '👨‍👨‍👧‍👦', '👨‍👨‍👦‍👦', '👨‍👨‍👧‍👧', '👩‍👩‍👦', '👩‍👩‍👧', '👩‍👩‍👧‍👦', '👩‍👩‍👦‍👦', '👩‍👩‍👧‍👧', '👨‍👦', '👨‍👦‍👦', '👨‍👧', '👨‍👧‍👦', '👨‍👧‍👧', '👩‍👦', '👩‍👦‍👦', '👩‍👧', '👩‍👧‍👦', '👩‍👧‍👧', '🗣', '👤', '👥', '🫂', '👣'],
  "Animals": ['🐶', '🐕', '🦮', '🐕‍🦺', '🐩', '🐺', '🦊', '🦝', '🐱', '🐈', '🐈‍⬛', '🦁', '🐯', '🐅', '🐆', '🐴', '🐎', '🦄', 'zebra', '🦌', '🐮', '🐂', '🐃', '🐄', '🐷', '🐖', '🐗', '🐽', '🐏', '🐑', 'goat', '🐪', '🐫', '🦙', '🦒', '🐘', '🦣', '🦏', '🦛', '🐭', '🐁', '🐀', '🐹', '🐰', '🐇', '🐿', '🦫', '🦔', '🦇', '🐻', '🐨', '🐼', '🦥', '🦦', '🦨', '🦘', '🦡', '🐾', '🦃', '🐔', '🐓', '🐣', '🐤', '🐥', '🐦', '🐧', '🕊', '🦅', 'duck', '🦢', '🦉', '🦤', '🪶', '🦩', '🦚', 'parrot', '🐸', '🐊', '🐢', '🦎', 'snake', '🐲', '🐉', '🦕', '🦖', '🐳', '🐋', '🐬', '🦭', 'fish', '🐠', '🐡', 'shark', 'octopus', '🐚', '🐌', '🦋', '🐛', 'ant', 'bee', '🪲', 'lady_beetle', 'cricket', 'spider', 'web', 'scorpion', 'mosquito', 'fly', 'worm', 'microbe', '💐', '🌸', '💮', '🏵', '🌹', '🥀', '🌺', 'sunflower', 'blossom', 'tulip', 'seedling', 'potted_plant', 'evergreen_tree', 'deciduous_tree', 'palm_tree', 'cactus', 'sheaf_of_rice', 'herb', 'shamrock', 'four_leaf_clover', 'maple_leaf', 'fallen_leaf', 'leaf_fluttering_in_wind'],
  "Food": ['🍇', '🍈', '🍉', '🍊', '🍋', '🍌', '🍍', '🥭', '🍎', '🍏', '🍐', '🍑', '🍒', '🍓', '🫐', '🥝', '🍅', '🫒', '🥥', '🥑', '🍆', '🥔', '🥕', '🌽', '🌶', '🫑', '🥒', '🥬', '🥦', '🧄', 'onion', 'mushroom', 'nut', 'chestnut', 'bread', 'croissant', 'baguette_bread', 'flatbread', 'pretzel', 'bagel', 'pancakes', 'waffle', 'cheese_wedge', 'meat_on_bone', 'poultry_leg', 'cut_of_meat', 'bacon', 'hamburger', 'fries', 'pizza', 'hotdog', 'sandwich', 'taco', 'burrito', 'tamale', 'stuffed_flatbread', 'falafel', 'egg', 'cooking', 'shallow_pan_of_food', 'pot_of_food', 'fondue', 'bowl_with_spoon', 'green_salad', 'popcorn', 'butter', 'salt', 'canned_food', 'bento', 'rice_cracker', 'rice_ball', 'cooked_rice', 'curry', 'steaming_bowl', 'spaghetti', 'roasted_sweet_potato', 'oden', 'sushi', 'fried_shrimp', 'fish_cake', 'moon_cake', 'dango', 'dumpling', 'fortune_cookie', 'takeout_box', 'crab', 'lobster', 'shrimp', 'squid', 'oyster', 'ice_cream', 'shaved_ice', 'ice_cream', 'doughnut', 'cookie', 'birthday', 'cake', 'cupcake', 'pie', 'chocolate_bar', 'candy', 'lollipop', 'custard', 'honey_pot', 'baby_bottle', 'glass_of_milk', 'coffee', 'teapot', 'teacup_without_handle', 'sake', 'champagne', 'wine_glass', 'cocktail', 'tropical_drink', 'beer', 'beers', 'clinking_glasses', 'tumbler_glass', 'cup_with_straw', 'bubble_tea', 'beverage_box', 'mate', 'ice', 'chopsticks', 'plate_with_cutlery', 'fork_and_knife', 'spoon', 'hocho', 'amphora'],
  "Activity": ['⚽', '🏀', '🏈', '⚾', '🥎', '🎾', '🏐', '🏉', '🥏', '🎱', '🪀', '🏓', '🏸', '🏒', '🏑', '🥍', 'cricket', '🪃', 'goal_net', '⛳', 'kite', 'bow_and_arrow', 'fishing_pole_and_fish', 'diving_mask', 'boxing_glove', 'martial_arts_uniform', 'running_shirt_with_sash', 'skateboard', 'roller_skate', 'sled', 'ice_skate', 'curling_stone', 'ski', 'skier', 'snowboarder', 'parachute', 'weight_lifter', 'wrestlers', 'person_cartwheeling', 'person_bouncing_ball', 'fencer', 'person_playing_handball', 'golfer', 'horse_racing', 'person_in_lotus_position', 'person_surfing', 'person_swimming', 'person_playing_water_polo', 'person_rowing_boat', 'person_climbing', 'person_mountain_biking', 'person_biking', 'trophy', '1st_place_medal', '2nd_place_medal', '3rd_place_medal', 'sports_medal', 'military_medal', 'rosette', 'reminder_ribbon', 'ticket', 'admission_tickets', 'circus_tent', 'juggler', 'performing_arts', 'ballet_shoes', 'artist_palette', 'clapper_board', 'microphone', 'headphone', 'musical_score', 'musical_keyboard', 'drum', 'saxophone', 'trumpet', 'guitar', 'banjo', 'violin', 'game_die', 'chess_pawn', 'bullseye', 'bowling', 'video_game', 'slot_machine', 'jigsaw'],
  "Travel": ['🚗', '🚕', '🚙', '🚌', '🚎', '🏎', '🚓', '🚑', '🚒', '🚐', '🛻', '🚚', '🚛', '🚜', '🦯', '🦽', '🦼', '🛴', '🚲', '🛵', '🏍', '🛺', '🚨', '🚔', '🚍', '🚘', '🚖', '🚡', '🚠', '🚟', '🚃', '🚋', '🚞', '🚝', '🚄', '🚅', '🚈', '🚂', '🚆', '🚇', '🚊', '🚉', '🚁', '🛩', '✈', '🛫', '🛬', '🚀', '🛰', '💺', 'canoe', 'sailboat', 'motor_boat', 'speedboat', 'ferry', 'passenger_ship', 'ship', 'anchor', 'construction', 'fuelpump', 'busstop', 'vertical_traffic_light', 'traffic_light', 'stop_sign', 'ferris_wheel', 'roller_coaster', 'carousel_horse', 'building_construction', 'foggy', 'tokyo_tower', 'factory', 'fountain', 'rice_scene', 'mountain', 'mountain_snow', 'mount_fuji', 'volcano', 'silhouette', 'camping', 'tent', 'national_park', 'motorway', 'railway_track', 'sunrise', 'sunrise_over_mountains', 'desert', 'beach_with_umbrella', 'desert_island', 'sunset', 'city_sunset', 'city_dusk', 'night_with_stars', 'bridge_at_night', 'milky_way', 'stars', 'sparkler', 'fireworks', 'zap', 'comet', 'boom', 'fire', 'tornado', 'rainbow', 'sunny', 'sun_with_face', 'new_moon_with_face', 'earth_africa', 'earth_americas', 'earth_asia', 'ringed_planet', 'dizzy', 'star', 'star2', 'sparkles', 'cloud', 'partly_sunny', 'thunder_cloud_and_rain', 'sun_behind_small_cloud', 'sun_behind_large_cloud', 'sun_behind_rain_cloud', 'cloud_with_rain', 'cloud_with_snow', 'cloud_with_lightning', 'cloud_with_tornado', 'fog', 'wind_blowing_face', 'cyclone', 'snowflake', 'snowman', 'snowman_without_snow', 'tanabata_tree', 'bamboo', 'dolls', 'flags', 'wind_chime', 'rice_scene', 'red_envelope', 'ribbon', 'gift', 'reminder_ribbon', 'admission_tickets', 'ticket', 'military_medal', 'trophy', 'sports_medal', '1st_place_medal', '2nd_place_medal', '3rd_place_medal', 'soccer', 'baseball', 'softball', 'basketball', 'volleyball', 'football', 'rugby_football', 'tennis', 'flying_disc', 'bowling', 'cricket_bat_and_ball', 'field_hockey_stick_and_ball', 'ice_hockey_stick_and_puck', 'lacrosse', 'ping_pong', 'badminton_racquet_and_shuttlecock', 'boxing_glove', 'martial_arts_uniform', 'climbing'],
  "Objects": ['⌚', '📱', '📲', '💻', '⌨', '🖥', '🖨', '🖱', '🖲', '🕹', '🗜', '💽', '💾', '💿', '📀', '📼', '📷', '📸', '📹', '🎥', '📽', '🎞', '📞', '☎', '📟', '📠', '📺', '📻', '🎙', '🎚', '🎛', '🧭', '⏱', '⏲', '⏰', '🕰', '⌛', '⏳', '📡', '🔋', '🔌', '💡', '🔦', '🕯', '🪔', '🧯', '🛢', '💸', '💵', '💴', '💶', '💷', '🪙', '💰', '💳', '💎', '⚖', '🪜', '🧰', '🪛', '🔧', '🔨', '⚒', '🛠', '⛏', '🪚', '🔩', '⚙', '🪤', '🧱', '⛓', '🧲', '🔫', '💣', '🧨', '🪓', '🔪', '🗡', '⚔', '🛡', '🚬', '⚰', '🪦', '⚱', '🏺', '🔮', '📿', '🧿', '💈', '⚗', '🔭', '🔬', '🕳', '🩹', '🩺', '💊', '💉', '🩸', '🧬', '🦠', '🧫', '🧪', '🌡', '🧹', '🪠', '🧺', '🧻', '🚽', '🚰', '🚿', '🛁', '🛀', '🧼', '🪥', '🪒', '🧽', '🪣', '🧴', '🛎', '🔑', '🗝', '🚪', '🪑', '🛋', '🛏', '🛌', '🧸', '🪆', '🖼', '🪞', '🪟', '🛍', '🛒', '🎁', '🎈', '🎏', '🎀', '🪄', '🪅', '🎊', '🎉', '🎎', '🪔', '🎐', '🧧', '✉', '📩', '📨', '📧', '💌', '📥', '📤', '📦', '🏷', '🪧', '📪', '📫', '📬', '📭', '📮', '📯', '📜', '📃', '📄', '📑', '🧾', '📊', '📈', '📉', '🗒', '🗓', '📆', '📅', '🗑', '📇', '🗃', '🗳', '🗄', '📋', '📁', '📂', '🗂', '🗞', '📰', '📓', '📔', '📒', '📕', '📗', '📘', '📙', '📚', '📖', '🔖', '🧷', '🔗', '📎', '🖇', '📐', '📏', '🧮', '📌', '📍', '✂', '🖊', '🖋', '✒', '🖌', '🖍', '📝', '✏', '🔍', '🔎', '🔏', '🔐', '🔒', '🔓'],
  "Symbols": ['❤', '🧡', '💛', '💚', '💙', '💜', '🤎', '🖤', '🤍', '💔', '❣', '💕', '💞', '💓', '💗', '💖', '💘', '💝', '💟', '☮', '✝', '☪', '🕉', '☸', '✡', '🔯', '🕎', '☯', '☦', '🛐', '⛎', '♈', '♉', '♊', '♋', '♌', '♍', '♎', '♏', '♐', '♑', '♒', '♓', '🆔', '⚛', '🉑', '☢', '☣', '📴', '📳', '🈶', '🈚', '🈸', '🈺', '🈷', '✴', '🆚', '💮', '🉐', '㊙', '㊗', '🈴', '🈵', '🈹', '🈲', '🅰', '🅱', '🆎', '🆑', '🅾', '🆘', '❌', '⭕', '🛑', '⛔', '📛', '🚫', '💯', '💢', '♨', '🚷', '🚯', '🚳', '🚱', '🔞', '📵', '🚭', '❗', '❕', '❓', '❔', '‼', '⁉', '🔅', '🔆', '〽', '⚠', '🚸', '🔱', '⚜', '🔰', '♻', '✅', '🈯', '💹', '❇', '✳', '❎', '🌐', '💠', 'Ⓜ', '🌀', '💤', '🏧', '🚾', '♿', '🅿', '🛗', '🈁', '🈂', '🛂', '🛃', '🛄', '🛅', '🚹', '🚺', '🚼', '🚻', '🚮', '🎦', '📶', '🈁', '🆖', '🆗', '🆙', '🆒', '🆕', '🆓', '0️⃣', '1️⃣', '2️⃣', '3️⃣', '4️⃣', '5️⃣', '6️⃣', '7️⃣', '8️⃣', '9️⃣', '🔟', '🔢', '#️⃣', '*️⃣', '⏏', '▶', '⏸', '⏯', '⏹', '⏺', '⏭', '⏮', '⏩', '⏪', '⏫', '⏬', '◀', '🔼', '🔽', '➡', '⬅', '⬆', '⬇', '↗', '↘', '↙', '↖', '↕', '↔', '↪', '↩', '⤴', '⤵', '🔀', '🔁', '🔂', '🔄', '🔃', '🎵', '🎶', '➕', '➖', '➗', '✖', '♾', '💲', '💱', '™', '©', '®', '〰', '➰', '➿', '🔚', '🔙', '🔛', '🔝', '🔜', '✔', '☑', '🔘', '🔴', '🟠', '🟡', '🟢', '🔵', '🟣', '🟤', '⚫', '⚪', '🟥', '🟧', '🟨', '🟩', '🟦', '🟪', '🟫', '⬛', '⬜', '◼', '◻', '◾', '◽', '▪', '▫', '🔸', '🔹', '🔶', '🔷', '🔺', '🔻', '💠', '🔘', '🔳', '🔲'],
  "Flags": ['🏁', '🚩', '🎌', '🏴', '🏳', '🏳️‍🌈', '🏳️‍⚧️', '🏴‍☠️', '🇦🇨', '🇦🇩', '🇦🇪', '🇦🇫', '🇦🇬', '🇦🇮', '🇦🇱', '🇦🇲', '🇦🇴', '🇦🇶', '🇦🇷', '🇦🇸', '🇦🇹', '🇦🇺', '🇦🇼', '🇦🇽', '🇦🇿', '🇧🇦', '🇧🇧', '🇧🇩', '🇧🇪', '🇧🇫', '🇧🇬', '🇧🇭', '🇧🇮', '🇧🇯', '🇧🇱', '🇧🇲', '🇧🇳', '🇧🇴', 'bq', '🇧🇷', '🇧🇸', '🇧🇹', '🇧🇻', '🇧🇼', '🇧🇾', '🇧🇿', '🇨🇦', '🇨🇨', '🇨🇩', '🇨🇫', '🇨🇬', '🇨🇭', '🇨🇮', '🇨🇰', '🇨🇱', '🇨🇲', '🇨🇳', '🇨🇴', '🇨🇵', '🇨🇷', '🇨🇺', '🇨🇻', '🇨🇼', '🇨🇽', '🇨🇾', '🇨🇿', '🇩🇪', '🇩🇬', '🇩🇯', '🇩🇰', '🇩🇲', '🇩🇴', '🇩🇿', '🇪🇦', '🇪🇨', '🇪🇪', '🇪🇬', '🇪🇭', '🇪🇷', '🇪🇸', '🇪🇹', '🇪🇺', '🇫🇮', '🇫🇯', '🇫🇰', '🇫🇲', '🇫🇴', '🇫🇷', '🇬🇦', '🇬🇧', '🇬🇩', '🇬🇪', '🇬🇫', '🇬🇬', '🇬🇭', '🇬🇮', '🇬🇱', '🇬🇲', '🇬🇳', '🇬🇵', '🇬🇶', '🇬🇷', '🇬🇸', '🇬🇹', '🇬🇺', '🇬🇼', '🇬🇾', '🇭🇰', '🇭🇲', '🇭🇳', '🇭🇷', '🇭🇹', '🇭🇺', '🇮🇨', '🇮🇩', '🇮🇪', '🇮🇱', '🇮🇲', '🇮🇳', '🇮🇴', '🇮🇶', '🇮🇷', '🇮🇸', '🇮🇹', '🇯🇪', '🇯🇲', '🇯🇴', '🇯🇵', '🇰🇪', '🇰🇬', '🇰🇭', '🇰🇮', '🇰🇲', '🇰🇳', '🇰🇵', '🇰🇷', '🇰🇼', '🇰🇾', '🇰🇿', '🇱🇦', '🇱🇧', '🇱🇨', '🇱🇮', '🇱🇰', '🇱🇷', '🇱🇸', '🇱🇹', '🇱🇺', '🇱🇻', '🇱🇾', '🇲🇦', '🇲🇨', '🇲🇩', '🇲🇪', '🇲🇫', '🇲🇬', '🇲🇭', '🇲🇰', '🇲🇱', '🇲🇲', '🇲🇳', '🇲🇴', '🇲🇵', '🇲🇶', '🇲🇷', '🇲🇸', '🇲🇹', '🇲🇺', '🇲🇻', '🇲🇼', '🇲🇽', '🇲🇾', '🇲Mz', '🇳🇦', '🇳🇨', '🇳🇪', '🇳🇫', '🇳🇬', '🇳🇮', '🇳🇱', '🇳🇴', '🇳🇵', '🇳🇷', '🇳🇺', '🇳🇿', '🇴🇲', '🇵🇦', '🇵🇪', '🇵🇫', '🇵🇬', '🇵🇭', '🇵🇰', '🇵🇱', '🇵🇲', '🇵🇳', '🇵🇷', '🇵🇸', '🇵🇹', '🇵🇼', '🇵🇾', '🇶🇦', '🇷🇪', '🇷🇴', '🇷🇸', '🇷🇺', '🇷🇼', '🇸🇦', '🇸🇧', '🇸🇨', '🇸🇩', '🇸🇪', '🇸🇬', '🇸🇭', '🇸🇮', '🇸🇯', '🇸🇰', '🇸🇱', '🇸🇲', '🇸🇳', '🇸🇴', '🇸🇷', '🇸🇸', '🇸🇹', '🇸🇻', '🇸🇽', '🇸🇾', '🇸🇿', '🇹🇦', '🇹🇨', '🇹🇩', '🇹🇫', '🇹🇬', '🇹🇭', '🇹🇯', '🇹🇰', '🇹🇱', '🇹🇲', '🇹🇳', '🇹🇴', '🇹🇷', '🇹🇹', '🇹🇻', '🇹🇼', '🇹🇿', '🇺🇦', '🇺🇬', '🇺🇲', '🇺🇳', '🇺🇸', '🇺🇾', '🇺🇿', '🇻🇦', '🇻🇨', '🇻🇪', '🇻🇬', '🇻🇮', '🇻🇳', '🇻🇺', '🇼🇫', '🇼🇸', '🇽🇰', '🇾🇪', '🇾🇹', '🇿🇦', '🇿🇲', '🇿🇼']
};

export const GIF_CATEGORIES = {
  "Sexy": [
    "https://media.giphy.com/media/l41lYcdbwjXqC1g3K/giphy.gif",
    "https://media.giphy.com/media/3o7TKyPpWvFrpwua2I/giphy.gif",
    "https://media.giphy.com/media/26FLdmIp6wJr91J4k/giphy.gif",
    "https://media.giphy.com/media/l0HlO3BJ8LALPW4sE/giphy.gif",
    "https://media.giphy.com/media/3o7TKs8b6ZIDchmUDe/giphy.gif",
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif",
    "https://media.giphy.com/media/l41lItp5qYy6g5Wlq/giphy.gif",
    "https://media.giphy.com/media/26BRL7YrutHKsVtOE/giphy.gif",
    "https://media.giphy.com/media/l0Iy5jWZFjb60dBxa/giphy.gif",
    "https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif",
    "https://media.giphy.com/media/l0HlCqV35hdEg2LS4/giphy.gif",
    "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif"
  ],
  "Funny": [
    "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif",
    "https://media.giphy.com/media/CoDp6NnSmItoY/giphy.gif",
    "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif",
    "https://media.giphy.com/media/26n6R5HOYsqr5I5lC/giphy.gif",
    "https://media.giphy.com/media/uaSFG9wjoK396/giphy.gif",
    "https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif",
    "https://media.giphy.com/media/l0HlHJGHe3yAMhdQY/giphy.gif",
    "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",
    "https://media.giphy.com/media/wW95fEq09hOI8/giphy.gif",
    "https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif",
    "https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif",
    "https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif",
    "https://media.giphy.com/media/l2JhtqIfG8i1mC2Ws/giphy.gif",
    "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif",
    "https://media.giphy.com/media/l0HlMh40gw8LvS5xu/giphy.gif"
  ],
  "Comedy": [
    "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif",
    "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif",
    "https://media.giphy.com/media/CoDp6NnSmItoY/giphy.gif",
    "https://media.giphy.com/media/26n6R5HOYsqr5I5lC/giphy.gif",
    "https://media.giphy.com/media/uaSFG9wjoK396/giphy.gif",
    "https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif",
    "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",
    "https://media.giphy.com/media/wW95fEq09hOI8/giphy.gif",
    "https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif",
    "https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif",
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/xT9DPBMumjWZw0tS5G/giphy.gif",
    "https://media.giphy.com/media/l0Ex9WXEmresJCKBO/giphy.gif",
    "https://media.giphy.com/media/xT9IGG50REtVl5hE8E/giphy.gif",
    "https://media.giphy.com/media/3o7527pa7qs9kCG78A/giphy.gif"
  ],
  "Boy": [
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/3o7TKs8b6ZIDchmUDe/giphy.gif",
    "https://media.giphy.com/media/l41lItp5qYy6g5Wlq/giphy.gif",
    "https://media.giphy.com/media/26BRL7YrutHKsVtOE/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/l0HlCqV35hdEg2LS4/giphy.gif",
    "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif",
    "https://media.giphy.com/media/l0HlO3BJ8LALPW4sE/giphy.gif",
    "https://media.giphy.com/media/26FLdmIp6wJr91J4k/giphy.gif",
    "https://media.giphy.com/media/3o7TKyPpWvFrpwua2I/giphy.gif",
    "https://media.giphy.com/media/xT5LMHxhOfscxPfIfu/giphy.gif",
    "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
    "https://media.giphy.com/media/xT9DPzhNGA8MKjxwlz/giphy.gif",
    "https://media.giphy.com/media/26AHtxxvP1p9YhM4M/giphy.gif",
    "https://media.giphy.com/media/l2JhtKvU4uLp1YfVS/giphy.gif"
  ],
  "Girl": [
    "https://media.giphy.com/media/l41lYcdbwjXqC1g3K/giphy.gif",
    "https://media.giphy.com/media/26BRv0ThflsHCqDrG/giphy.gif",
    "https://media.giphy.com/media/l0Iy5jWZFjb60dBxa/giphy.gif",
    "https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif",
    "https://media.giphy.com/media/xT9IgG50Fb7Mi0prBC/giphy.gif",
    "https://media.giphy.com/media/l0HlMh40gw8LvS5xu/giphy.gif",
    "https://media.giphy.com/media/l2JhtqIfG8i1mC2Ws/giphy.gif",
    "https://media.giphy.com/media/26gsjCZpPolPr3sBy/giphy.gif",
    "https://media.giphy.com/media/3o7TKSjRrfIPjeiVyM/giphy.gif",
    "https://media.giphy.com/media/l0HlHJGHe3yAMhdQY/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/xT5LMHxhOfscxPfIfu/giphy.gif",
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
    "https://media.giphy.com/media/xT9DPzhNGA8MKjxwlz/giphy.gif"
  ],
  "Laugh": [
    "https://media.giphy.com/media/10JhviFuU2gWD6/giphy.gif",
    "https://media.giphy.com/media/CoDp6NnSmItoY/giphy.gif",
    "https://media.giphy.com/media/3oEjHAUOqG3lSS0f1C/giphy.gif",
    "https://media.giphy.com/media/26n6R5HOYsqr5I5lC/giphy.gif",
    "https://media.giphy.com/media/uaSFG9wjoK396/giphy.gif",
    "https://media.giphy.com/media/13CoXDiaCcCoyk/giphy.gif",
    "https://media.giphy.com/media/JIX9t2j0ZTN9S/giphy.gif",
    "https://media.giphy.com/media/wW95fEq09hOI8/giphy.gif",
    "https://media.giphy.com/media/tXL4FHPSnVJ0A/giphy.gif",
    "https://media.giphy.com/media/3o6ozvv0zsJskzOCbu/giphy.gif",
    "https://media.giphy.com/media/l0Ex9WXEmresJCKBO/giphy.gif",
    "https://media.giphy.com/media/xT9IGG50REtVl5hE8E/giphy.gif",
    "https://media.giphy.com/media/3o7527pa7qs9kCG78A/giphy.gif",
    "https://media.giphy.com/media/l0MYH8Q83CXvSCzXy/giphy.gif",
    "https://media.giphy.com/media/l3fQf1OEAq0iri9RC/giphy.gif"
  ],
  "Angry": [
    "https://media.giphy.com/media/11tTNkNy1SdXGg/giphy.gif",
    "https://media.giphy.com/media/l1J9u3TZfpmeDLkD6/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/l0HlCqV35hdEg2LS4/giphy.gif",
    "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif",
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/3o7TKs8b6ZIDchmUDe/giphy.gif",
    "https://media.giphy.com/media/l41lItp5qYy6g5Wlq/giphy.gif",
    "https://media.giphy.com/media/26BRL7YrutHKsVtOE/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/xT5LMHxhOfscxPfIfu/giphy.gif",
    "https://media.giphy.com/media/l41lYcdbwjXqC1g3K/giphy.gif",
    "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
    "https://media.giphy.com/media/xT9DPzhNGA8MKjxwlz/giphy.gif",
    "https://media.giphy.com/media/26AHtxxvP1p9YhM4M/giphy.gif"
  ],
  "Stress": [
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/l0HlCqV35hdEg2LS4/giphy.gif",
    "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif",
    "https://media.giphy.com/media/l0HlP2ms0eUc5nlHG/giphy.gif",
    "https://media.giphy.com/media/3o7TKs8b6ZIDchmUDe/giphy.gif",
    "https://media.giphy.com/media/l41lItp5qYy6g5Wlq/giphy.gif",
    "https://media.giphy.com/media/26BRL7YrutHKsVtOE/giphy.gif",
    "https://media.giphy.com/media/3o7TKr3nzbh5RfBb4A/giphy.gif",
    "https://media.giphy.com/media/l0HlCqV35hdEg2LS4/giphy.gif",
    "https://media.giphy.com/media/3o7TKoWXm3okO1kgHC/giphy.gif",
    "https://media.giphy.com/media/xT5LMHxhOfscxPfIfu/giphy.gif",
    "https://media.giphy.com/media/l41lYcdbwjXqC1g3K/giphy.gif",
    "https://media.giphy.com/media/3o6Zt481isNVuQI1l6/giphy.gif",
    "https://media.giphy.com/media/xT9DPzhNGA8MKjxwlz/giphy.gif",
    "https://media.giphy.com/media/26AHtxxvP1p9YhM4M/giphy.gif"
  ]
};